FROM python:3.12-slim AS build
WORKDIR /app
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

FROM build AS final
WORKDIR /app
COPY src ./src
COPY main.py .
COPY .env .
ENV PYTHONUNBUFFERED=1

ENTRYPOINT python main.py
